<a href="https://colab.research.google.com/github/erkansengonul/aiworkstr/blob/main/LinearRegression_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [13]:
x = np.array([2743, 3518, 1855, 5214, 4341]).reshape((-1, 1))
y = np.array([21.4, 15.2, 38.9, 12.7, 17.8])

In [14]:
print(x)

[[2743]
 [3518]
 [1855]
 [5214]
 [4341]]


In [15]:
print(y)

[21.4 15.2 38.9 12.7 17.8]


In [16]:
model = LinearRegression()
model.fit(x, y)
model = LinearRegression().fit(x, y)

coefficient of determination (𝑅²) 

In [17]:
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)

coefficient of determination: 0.7310099894107271


Y = (model.coef_ * X) + (model.intercept_)

Y = -0.00676497 * X + 45.10875557270988

In [20]:
print('intercept:', model.intercept_)
print('slope:', model.coef_)

intercept: 45.10875557270988
slope: [-0.00676497]


In [25]:
y_pred = model.predict(x)
print('predicted y:', y_pred, sep='\n')

predicted y:
[26.55244395 21.30959251 32.55973696  9.83620406 15.74202252]


In [29]:
from sklearn import metrics

mae = metrics.mean_absolute_error(y, y_pred)
mse = metrics.mean_squared_error(y, y_pred)


print('MAE:', mae)
print('MSE:', mse)


MAE: 4.504814583148205
MSE: 23.30206663732752


In [43]:
distance = y-y_pred
print('Distance between y_true and y_pred:', distance)

squared_distance = np.square(distance)
print('Distance between y_true and y_pred (Square):', squared_distance)

absolute_distance = np.absolute(distance)
print('Distance between y_true and y_pred (Absolute):', absolute_distance)

print('Mean Absolute Error', np.sum(absolute_distance) / np.size(absolute_distance))
print('Mean Squared Error', np.sum(squared_distance) / np.size(absolute_distance))


Distance between y_true and y_pred: [-5.15244395 -6.10959251  6.34026304  2.86379594  2.05797748]
Distance between y_true and y_pred (Square): [26.54767866 37.32712061 40.19893544  8.20132719  4.23527129]
Distance between y_true and y_pred (Absolute): [5.15244395 6.10959251 6.34026304 2.86379594 2.05797748]
Mean Absolute Error 4.504814583148205
Mean Squared Error 23.30206663732752
